### ISSUE TITLE
Burger Icon Bug

### ISSUE THREAD

**Issue by Sentinail** [Sentinail/gab-express#3]
How to recreate?

Shrink the display in x-axis until the burger is visible, click the burger and click any links and see how the burger Icon reacts,

What Should Happen?

When the navbar is open the burger Icon should be "X", when the navbar is closed the burger icon should be a "Burger"

**Comment by ikarpushyn** [comment]
The problem was that the isNavbarVisible state, which is responsible for displaying/hiding the menu, was in the Header component. When you clicked on a link inside the menu, the route would be updated, the Header would be rendered, and the isNavbarVisible state would be set back to its original value (false), hiding the menu.

**Comment by Sentinail** [comment]
Thank you for your pull request! I've reviewed your changes and I appreciate your contribution. 
I accept the pull request. Regarding the "isActive" state of the Burger component, 
it determines whether it should display an "X" or a "burger" (sorry for my wording) icon. I noticed that you 
passed the "isNavbarVisible" state from the Header component to the Burger component, 
which allows it to be synchronized with the navbar's visibility state.
Once again, thank you for your contribution. I will merge your pull request into the main 
branch. If you have any further suggestions or improvements, feel free to let me know.
